services:
  - type: web
    name: hackathon-backend
    runtime: node
    buildCommand: npm install --production && npm run build && npm run build:minimal
    startCommand: npm run start:minimal
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=150 --optimize-for-size --gc-interval=50 --max-new-space-size=32
      - key: DATABASE_URL
        sync: false # À définir manuellement
      - key: JWT_SECRET
        sync: false # À définir manuellement
      - key: PORT
        value: 10000
    healthCheckPath: /health
